### ISSUE TITLE
Unable to leverage advanced connstring arguments in indexer

### ISSUE THREAD

**Issue by jan-zmeskal** [quay/claircore#309]
When I was reading the code of `pgxpool` library, I realized that user should be able to enrich PostgreSQL connstring by advanced arguments that are parsed by `pgxpool`. See the [ParseConfig](https://github.com/jackc/pgx/blob/3568b908c03beaf0846015658ca9fd3123c51823/pgxpool/pool.go#L231) function. However, if you actually try to do that, you'll get this:
![image](https://user-images.githubusercontent.com/22600243/107523700-4e30b680-6bb5-11eb-81a8-c132aadf6238.png)

I was running indexer with these settings:
```
indexer:
  connstring: host=<censored> port=5432 dbname=<censored> user=<censored> password=xGCkO0BnzSUpOVF9iz3L5wCiHef6SVslIztpWmcayciD57qHWH sslmode=disable application_name=clair-indexer pool_max_conns=1 pool_max_conn_idle_time=5m0s
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: True
```
Workaround is to set migrations to `False`. However, long-term, I need to run indexer with migrations set to `True`.
